毎回実行

In [1]:
import numpy as np

array：リストかタプルで配列をつくる

In [2]:
a = np.array([0,1,2])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[0 1 2]
int32


In [4]:
b = np.array([1,1.5,2])
print(b)
print(b.dtype)

c = np.array([1 + 2j,3 + 4j,5 + 6j])
print(c)
print(c.dtype)

d = np.array([True,False,True,False,False])
print(d)
print(d.dtype)

e = np.array(list("TechAcademy"))
print(e)
print(e.dtype)

[1.  1.5 2. ]
float64
[1.+2.j 3.+4.j 5.+6.j]
complex128
[ True False  True False False]
bool
['T' 'e' 'c' 'h' 'A' 'c' 'a' 'd' 'e' 'm' 'y']
<U1


In [5]:
f = np.array([100,200,300],dtype = np.int16)
print(f)
print(f.dtype)

[100 200 300]
int16


np.arange：連続する整数値

In [7]:
a = np.arange(20)
print(a)

b = np.arange(1,21)
print(b)

c = np.arange(2,41,2)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


np.linspace(a,b,c)：a以上b以下をc分割

In [8]:
d = np.linspace(0,10,5)
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [9]:
d = np.linspace(0,10,6)
print(d)

[ 0.  2.  4.  6.  8. 10.]


np.empty：初期値無し

In [10]:
e = np.empty(5)
print(e)

[ 2.  4.  6.  8. 10.]


np.zeros：初期値0,
np.ones：初期値1

In [12]:
f = np.zeros(5)
print(f)

[0. 0. 0. 0. 0.]


np.random.rand：0以上1未満ランダム初期値

In [13]:
g = np.random.rand(5)
print(g)

[0.44858254 0.18511905 0.02170165 0.55082851 0.40442436]
